<!-- ${FRAMEWORK_SLUG}-generated framework_version=${FRAMEWORK_VERSION} generated_at=${GENERATED_AT} input_hash=${INPUT_HASH} -->

# ${BRAND_NAME} — Coding Standards

This file is loaded by Claude Code at session start. Keep it under **200 lines** and within **150 RFC-2119 directives** (counted by `\b(MUST|SHALL|SHOULD|MAY)(\s+NOT)?\b`). Move detail into `.claude/rules/` files when this file grows.

## Architecture

<!-- ARCHITECTURE_RULES -->

## Testing

<!-- TEST_METHODOLOGY_RULES -->

<!-- TEST_FRAMEWORK_RULES -->

## Security

<!-- SECURITY_FRAMEWORK_RULES -->

<!-- SECURITY_TOOLING_RULES -->

## General

- Code MUST follow existing conventions in the surrounding codebase.
- Public functions and classes SHOULD have a one-sentence purpose comment.
- Comments SHOULD explain *why* the code is shaped this way; the code itself explains *what*.
- Secrets MUST NOT appear in committed files.

<!-- ${FRAMEWORK_NAME}:DYNAMIC-LOAD-ANCHOR -->

<!--
This file was generated by ${FRAMEWORK_NAME} v${FRAMEWORK_VERSION}.
The team's steward owns ongoing edits via PR review against `.claude/`.
See branding/BRANDING.md §Governance for the steward role.
-->
